### PR TITLE
Create 09.using-gantry-syntax.md

### PR DESCRIPTION
**Pull request by hennysmafter**
As I am receiving a lot of question about using Gantry Syntax in Custom HTML modules I went on and created a section for it in the docs. As nr. 9 was missing I created it under that number. Please review the location maybe this fits better somewhere else. I though this would be the best fit. I will be adding more in future but would like to see this get merged with the main branch a.s.a.p that way I don't keep repeating myself on the chat.

### CODE REVIEW

**Comment by mahagr** [comment]
Generally I like to have section like this, but it could really go even slightly deeper on explaining nucleus grid system. Good start though!

**Comment by RyanMPierson** [comment]
Closing this one per notes above. Not discouraging another submission. It just wouldn't be able to go live as-is.

**Comment by mahagr** [comment]
Regarding to wrapper, its a new feature in Gantry 5.2 layout: any div tag that isn't part of the nucleus grid system but is used for CSS in the theme.

**Comment by hennysmafter** [comment]
Oh I don't mind that it won't go online as is. I rather have this discussion and make a good page! Then a half baked one. I also want to explain the entire grid and all the options with code examples and everything. But I won't be able to do that all at once. So please allow me to start and add to it! 
Could someone give a code example of the wrapper or link. 

@mahagr I am sorry but I don't understand your comment I read it three times but it ain't ringing bells. Would you please reformat it. Thank you in advance.

Title would better become: The building blocks of Gantry explained
Area: Advanced > Gantry Building Blocks Explained

**Comment by RyanMPierson** [comment]
Since it's documentation, could the title be a bit more direct? something like: Nucleus Grid System

**Comment by mahagr** [comment]
I meant that we added `wrapper` into 5.2, which basically allow nested divs in the layout.

**Pull request closed without merging**
